services:
  - type: web
    name: backend-tecplin
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: tecplin-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: EMAIL_HOST
        value: smtp.ethereal.email
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: STORAGE_BUCKET
        sync: false
      - key: STORAGE_ACCOUNT_ID
        sync: false
      - key: STORAGE_ENDPOINT
        sync: false
      - key: STORAGE_PUBLIC_URL
        sync: false
      - key: STORAGE_REGION
        value: auto
      - key: STORAGE_ACCESS_KEY
        sync: false
      - key: STORAGE_SECRET_KEY
        sync: false

databases:
  - name: tecplin-db
    plan: free
    databaseName: tecplin
    user: tecplin_user
